// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB4DzQdM_ZR8OmtVU47-gcZqEAziys18Y',
    appId: '1:769498891831:web:a92a2a1c23449834d3a1b2',
    messagingSenderId: '769498891831',
    projectId: 'stream-share-880b4',
    authDomain: 'stream-share-880b4.firebaseapp.com',
    storageBucket: 'stream-share-880b4.appspot.com',
    measurementId: 'G-D742PY6RSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCoNPzh0ZPmuwTVsu8SibQ4Tl-4EJWn8A',
    appId: '1:769498891831:android:f2753bb3c2b3931bd3a1b2',
    messagingSenderId: '769498891831',
    projectId: 'stream-share-880b4',
    storageBucket: 'stream-share-880b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVAUoAGDiftv1SSPpuT9tHqP1RsQNnQy4',
    appId: '1:769498891831:ios:2d86de94c9161ff4d3a1b2',
    messagingSenderId: '769498891831',
    projectId: 'stream-share-880b4',
    storageBucket: 'stream-share-880b4.appspot.com',
    iosBundleId: 'com.example.streamShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVAUoAGDiftv1SSPpuT9tHqP1RsQNnQy4',
    appId: '1:769498891831:ios:8b59df60500c4d8cd3a1b2',
    messagingSenderId: '769498891831',
    projectId: 'stream-share-880b4',
    storageBucket: 'stream-share-880b4.appspot.com',
    iosBundleId: 'com.example.streamShare.RunnerTests',
  );
}
